#include "stm32h7xx_hal.h"
#include "lfs.h"
#include "littlefs_qspi.h"
#include "w25q_mem.h"
// External QSPI handle generated by CubeMX
extern QSPI_HandleTypeDef hqspi;

// --- W25Q128 command set ---
#define CMD_READ_ID          0x9F
#define CMD_READ_DATA        0x03
#define CMD_FAST_READ        0x0B
#define CMD_PAGE_PROGRAM     0x02
#define CMD_SECTOR_ERASE     0x20
#define CMD_CHIP_ERASE       0xC7
#define CMD_WRITE_ENABLE     0x06
#define CMD_READ_STATUS_REG1 0x05

// --- Flash geometry ---
#define W25Q_SIZE       (16*1024*1024)   // 16 MB
#define W25Q_BLOCK_SIZE (4*1024)         // 4 KB erase sector
#define W25Q_PAGE_SIZE  (256)            // 256 B program page

// --- Utility: wait until WIP bit clears ---
static void qspi_wait_busy(void) {
    uint8_t status;
    QSPI_CommandTypeDef cmd = {
        .Instruction = CMD_READ_STATUS_REG1,
        .AddressMode = QSPI_ADDRESS_NONE,
        .DataMode = QSPI_DATA_1_LINE,
        .DummyCycles = 0,
        .NbData = 1,
    };
    do {
        HAL_QSPI_Command(&hqspi, &cmd, HAL_QSPI_TIMEOUT_DEFAULT_VALUE);
        HAL_QSPI_Receive(&hqspi, &status, HAL_QSPI_TIMEOUT_DEFAULT_VALUE);
    } while (status & 0x01); // WIP bit
}

// --- Utility: write enable ---
static void qspi_write_enable(void) {
    QSPI_CommandTypeDef cmd = {
        .Instruction = CMD_WRITE_ENABLE,
        .AddressMode = QSPI_ADDRESS_NONE,
        .DataMode = QSPI_DATA_1_LINE,
        .DummyCycles = 0,
        .NbData = 0,
    };
    HAL_QSPI_Command(&hqspi, &cmd, HAL_QSPI_TIMEOUT_DEFAULT_VALUE);
}

// --- LittleFS block device functions ---

int qspi_read(const struct lfs_config *c, lfs_block_t block,
              lfs_off_t off, void *buffer, lfs_size_t size) {



  W25Q_STATE state;
  uint32_t addr = block * c->block_size + off;


#if 0
    QSPI_CommandTypeDef cmd = {
        .Instruction = CMD_FAST_READ,
        .Address = addr,
        .AddressSize = QSPI_ADDRESS_24_BITS,
        .DataMode = QSPI_DATA_1_LINE, // start with single line
        .DummyCycles = 6,
        .NbData = size,
    };

    if (HAL_QSPI_Command(&hqspi, &cmd, HAL_QSPI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
        return -1;
    if (HAL_QSPI_Receive(&hqspi, buffer, HAL_QSPI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
        return -1;
#endif

    state = W25Q_ReadRaw(buffer, size, addr);
    if (state == W25Q_OK)
    	return 0;
    else
    	return -1;
}

int qspi_prog(const struct lfs_config *c, lfs_block_t block,
              lfs_off_t off, const void *buffer, lfs_size_t size) {
    uint32_t addr = block * c->block_size + off;

    const uint8_t *buf = buffer;
    W25Q_STATE state;

    while (size > 0) {
       uint32_t chunk = W25Q_PAGE_SIZE - (addr % W25Q_PAGE_SIZE);
       if (chunk > size) chunk = size;

       state = W25Q_ProgramRaw(buf, chunk, addr) ;
       if (state != W25Q_OK)
       	return -1;
#if 0
        qspi_write_enable();

        QSPI_CommandTypeDef cmd = {
            .Instruction = CMD_PAGE_PROGRAM,
            .Address = addr,
            .AddressSize = QSPI_ADDRESS_24_BITS,
            .DataMode = QSPI_DATA_1_LINE,
            .NbData = chunk,
        };

        if (HAL_QSPI_Command(&hqspi, &cmd, HAL_QSPI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
            return -1;
        if (HAL_QSPI_Transmit(&hqspi, (uint8_t*)buf, HAL_QSPI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
            return -1;

        qspi_wait_busy();
#endif

        addr += chunk;
        buf  += chunk;
        size -= chunk;
    }
    return 0;
}

int qspi_erase(const struct lfs_config *c, lfs_block_t block) {
//    uint32_t secAddr = block * c->block_size / 256;
    W25Q_STATE state;

    // Erase specified sector, not the raw address!!
    state = W25Q_EraseSector(block);

    if (state == W25Q_OK)
    	return 0;
    else
    	return -1;
#if 0
    qspi_write_enable();

    QSPI_CommandTypeDef cmd = {
        .Instruction = CMD_SECTOR_ERASE,
        .Address = addr,
        .AddressSize = QSPI_ADDRESS_24_BITS,
        .DataMode = QSPI_DATA_1_LINE,
    };

    if (HAL_QSPI_Command(&hqspi, &cmd, HAL_QSPI_TIMEOUT_DEFAULT_VALUE) != HAL_OK)
        return -1;

    qspi_wait_busy();

#endif

//    return 0;
}

int qspi_sync(const struct lfs_config *c) {
    // Nothing special, just ensure all ops complete
    return 0;
}

// --- LittleFS config instance ---
struct lfs_config qspi_lfs_cfg = {
    .read  = qspi_read,
    .prog  = qspi_prog,
    .erase = qspi_erase,
    .sync  = qspi_sync,

	.read_size    = W25Q_PAGE_SIZE,
	.prog_size    = W25Q_PAGE_SIZE,
    .block_size   = W25Q_BLOCK_SIZE,
    .block_count  = W25Q_SIZE / W25Q_BLOCK_SIZE,
	.block_cycles = 500,
    .cache_size   = W25Q_PAGE_SIZE * 2,
    .lookahead_size = W25Q_PAGE_SIZE,
};
